version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 7.0.0-alpha05
    - 7.0.0-alpha06
    - 7.0.0-alpha07
    - 7.0.0-alpha08
    - 7.0.0-alpha09
    - 7.0.0-alpha10
    - 7.0.0-alpha11
    - 7.0.0-alpha12
    - 7.0.0-alpha13
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: androidx.activity:activity-ktx
    versions:
    - 1.2.0
    - 1.2.1
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.5
    - 1.10.6
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.2-native-mt
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
